# docker-compose.yml

version: '3.9'

services:
  fastapi_app:
    build: .
    container_name: customer-recommender-app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    restart: always

  scheduler:
    build: .
    container_name: customer-recommender-scheduler
    command: ["python", "scheduler/main.py"]
    volumes:
      - .:/usr/src/app
    restart: always
